# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e85d01fd3de60353bc3f9cb5e23e460f00e7d571eeba8a626a9bbb747fcce8f8c5f7d001c912c926d296ae0765af3ae6f27af8fc5b551cb5e829b4298c2e410

test:
  secret_key_base: bfe8c6996aec08ada678d7cb4d9213d06d09cfe40a15e639828dc519deff1baee166931c281a32a49cda0d54e88508f173d6294be19230c2b30edf965654f7ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
